#!/usr/bin/env python3
"""Draw maki's home screen icons and write them as src/lib.rs.

64x64, 1 bit, drawn procedurally like the launcher's splash (no image tools needed).
Each icon is 64 rows of two 32-bit words: pixel x of row y is bit x % 32 of word
2y + x // 32, least significant bit first, and a set bit is a dark pixel. The launcher
places them in its 128x128 bitmaps.

    python3 icons.py [--preview OUT.png]
"""
import math
import pathlib
import struct
import sys
import zlib

S = 64


def disc(x, y, cx, cy, r):
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def ring(x, y, cx, cy, r, w):
    return abs(math.hypot(x - cx, y - cy) - r) <= w / 2


def seg(x, y, a, b, w):
    (ax, ay), (bx, by) = a, b
    dx, dy = bx - ax, by - ay
    t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)))
    px, py = ax + t * dx, ay + t * dy
    return (x - px) ** 2 + (y - py) ** 2 <= (w / 2) ** 2


def authenticator(x, y):
    """A stopwatch: codes that change with time."""
    cx, cy = 32, 36
    return (
        ring(x, y, cx, cy, 21, 4)
        or seg(x, y, (32, 9), (32, 14), 5)           # stem
        or seg(x, y, (27, 8), (37, 8), 4)            # crown
        or seg(x, y, (48, 17), (51, 14), 4)          # button
        or seg(x, y, (cx, cy), (cx, 22), 4)          # hands
        or seg(x, y, (cx, cy), (43, cy + 6), 4)
    )


def passwords(x, y):
    """A key."""
    return (
        ring(x, y, 19, 32, 10, 5)
        or seg(x, y, (29, 32), (57, 32), 5)
        or seg(x, y, (50, 32), (50, 42), 5)
        or seg(x, y, (57, 32), (57, 40), 5)
    )


def passkeys(x, y):
    """Someone, and a key: a login that's you, not a password."""
    person = disc(x, y, 25, 21, 9) or (y <= 53 and (x - 25) ** 2 / 17 ** 2 + (y - 54) ** 2 / 17 ** 2 <= 1)
    key = ring(x, y, 44, 44, 6, 3) or seg(x, y, (50, 44), (60, 44), 3) or seg(x, y, (57, 44), (57, 50), 3)
    gap = disc(x, y, 44, 44, 10) and not key  # a dark border so the key reads over the shoulder
    return (person and not gap) or key


def bitcoin(x, y):
    """A coin with the bitcoin sign."""
    coin = ring(x, y, 32, 32, 27, 3)
    stem = seg(x, y, (25, 18), (25, 46), 4)
    upper = seg(x, y, (25, 18), (35, 18), 4) or seg(x, y, (25, 32), (35, 32), 4) or (x >= 35 and ring(x, y, 35, 25, 7, 4))
    lower = seg(x, y, (25, 32), (37, 32), 4) or seg(x, y, (25, 46), (37, 46), 4) or (x >= 37 and ring(x, y, 37, 39, 7, 4))
    ticks = any(seg(x, y, (tx, a), (tx, b), 3) for tx in (29, 34) for a, b in ((12, 18), (46, 52)))
    return coin or stem or upper or lower or ticks


def settings(x, y):
    """A gear."""
    r = math.hypot(x - 32, y - 32)
    a = (math.degrees(math.atan2(y - 32, x - 32)) + 360) % 45
    tooth = r <= 25 and (a <= 11 or a >= 34)
    return (r <= 19 or tooth) and r > 8


ICONS = [
    ("AUTHENTICATOR", authenticator),
    ("PASSWORDS", passwords),
    ("PASSKEYS", passkeys),
    ("BITCOIN", bitcoin),
    ("SETTINGS", settings),
]


def pixels(f):
    # sample each pixel at its centre
    return [[f(x + 0.5, y + 0.5) for x in range(S)] for y in range(S)]


def to_words(px):
    words = []
    for y in range(S):
        for half in range(2):
            w = 0
            for bit in range(32):
                if not px[y][half * 32 + bit]:  # lit pixels are the drawing; set bits are dark
                    w |= 1 << bit
            words.append(w)
    return words


def write_rs(path):
    out = [
        "//! Icons for maki's home screen. Generated by icons.py -- edit that, not this.",
        "#![no_std]",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        "",
        "/// Icons are this many pixels square.",
        "pub const SIZE: usize = 64;",
        "",
        "/// 64 rows of two words: pixel x of row y is bit x % 32 of word 2y + x / 32, least",
        "/// significant bit first. A set bit is a dark pixel.",
        "pub type Icon = [u32; 128];",
    ]
    for name, f in ICONS:
        words = to_words(pixels(f))
        out.append("")
        out.append(f"pub const {name}: Icon = [")
        for i in range(0, len(words), 8):
            out.append("  " + ", ".join(f"0x{w:08x}" for w in words[i:i + 8]) + ",")
        out.append("];")
    pathlib.Path(path).write_text("\n".join(out) + "\n")


def write_png(path, scale=3, gap=8):
    icons = [pixels(f) for _, f in ICONS]
    w = len(icons) * (S + gap) - gap
    rows = []
    for y in range(S * scale):
        row = bytearray()
        for i, px in enumerate(icons):
            row += bytes(255 if px[y // scale][x // scale] else 0 for x in range(S * scale))
            if i < len(icons) - 1:
                row += bytes([60] * gap * scale)
        rows.append(b"\x00" + bytes(row))
    raw = b"".join(rows)

    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)

    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w * scale, S * scale, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    pathlib.Path(path).write_bytes(png)


if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent
    write_rs(here / "src" / "lib.rs")
    if "--preview" in sys.argv:
        write_png(sys.argv[sys.argv.index("--preview") + 1])
