#!/usr/bin/env python3
"""Draw Status's big letters and write them as src/font.rs.

maki's own fonts stop at 19 pixels; a status to read across a room wants more. This renders
printable ASCII from Cantarell ExtraBold (GNOME's interface font; SIL Open Font License 1.1,
which lets it be embedded in software) at three sizes, 1 bit with no smoothing, each glyph
cropped to its ink across and to the size's common line height down, in the bitmaps
`screen::blit` draws: rows of (width + 7) / 8 bytes, the leftmost pixel in the top bit.

    python3 assets/font.py [--font FILE]
"""
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/abattis-cantarell-fonts/Cantarell-ExtraBold.otf"
SIZES = {"BIG": 42, "MEDIUM": 27, "SMALL": 20}
CHARS = [chr(c) for c in range(32, 127)]


def render(font_path, size):
    font = ImageFont.truetype(font_path, size)
    pad = size
    ims = {}
    for ch in CHARS:
        im = Image.new("1", (size * 3, size * 3), 0)
        d = ImageDraw.Draw(im)
        d.fontmode = "1"
        d.text((pad, pad), ch, font=font, fill=1)
        ims[ch] = im
    # the line: from the highest ink to the lowest, over every glyph
    boxes = {ch: im.getbbox() for ch, im in ims.items()}
    inked = [b for b in boxes.values() if b]
    top = min(b[1] for b in inked)
    bottom = max(b[3] for b in inked)
    glyphs = []
    for ch in CHARS:
        advance = round(font.getlength(ch))
        box = boxes[ch]
        if box is None:
            glyphs.append((ch, advance, 0, 0, b""))
            continue
        l, _, r, _ = box
        cell = ims[ch].crop((l, top, r, bottom))
        w = r - l
        rows = bytearray()
        for y in range(bottom - top):
            row = 0
            for x in range(w):
                if cell.getpixel((x, y)):
                    row |= 1 << (((w + 7) // 8) * 8 - 1 - x)
            rows += row.to_bytes((w + 7) // 8, "big")
        glyphs.append((ch, advance, l - pad, w, bytes(rows)))
    return bottom - top, glyphs


def to_rust(fonts):
    out = [
        "// Generated by assets/font.py -- edit that, not this.",
        "// Cantarell ExtraBold (SIL Open Font License 1.1), printable ASCII, rendered 1 bit.",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        "",
        "/// A glyph: how far the pen moves after it, where its ink starts from the pen, how wide",
        "/// the ink is, and where its rows start in the font's bits.",
        "pub struct Glyph { pub advance: u8, pub left: i8, pub width: u8, pub at: u16 }",
        "",
        "/// Letters of one size: `height` rows each, for the characters from ' ' to '~'.",
        "pub struct Font { pub height: i32, pub glyphs: &'static [Glyph; 95], pub bits: &'static [u8] }",
        "",
    ]
    for name, (height, glyphs) in fonts.items():
        at = 0
        entries = []
        bits = bytearray()
        for ch, advance, left, width, rows in glyphs:
            entries.append(f"Glyph {{ advance: {advance}, left: {left}, width: {width}, at: {at} }}, // {ch!r}")
            bits += rows
            at += len(rows)
        assert at < 65536
        out.append(f"const {name}_GLYPHS: [Glyph; 95] = [")
        out += ["    " + e for e in entries]
        out.append("];")
        out.append(f"const {name}_BITS: [u8; {len(bits)}] = [")
        for i in range(0, len(bits), 24):
            out.append("    " + ", ".join(str(b) for b in bits[i : i + 24]) + ",")
        out.append("];")
        out.append(f"pub const {name}: Font = Font {{ height: {height}, glyphs: &{name}_GLYPHS, bits: &{name}_BITS }};")
        out.append("")
    return "\n".join(out)


def main():
    font_path = sys.argv[sys.argv.index("--font") + 1] if "--font" in sys.argv else FONT
    fonts = {name: render(font_path, size) for name, size in SIZES.items()}
    here = pathlib.Path(__file__).resolve().parent.parent
    (here / "src" / "font.rs").write_text(to_rust(fonts))
    for name, (height, glyphs) in fonts.items():
        print(name, SIZES[name], "px:", height, "rows,", sum(len(g[4]) for g in glyphs), "bytes")


main()
