#!/usr/bin/env python3
"""Draw the screensaver clock's digits and write them as src/clock_face.rs.

Big digits for a clock that fills maki's screen: the hours over the minutes, two digits a
row. Rendered once, here, from Cantarell ExtraBold (GNOME's interface font; SIL Open Font
License 1.1, which lets it be used and embedded in software), 1 bit with no smoothing,
cropped to the ink, then one fixed cell per digit so the clock doesn't shift as it ticks.
A dash stands in for the digits while maki doesn't know the time.

    python3 assets/clock.py [--preview OUT.png] [--font FILE]

Each glyph is CELL_H rows of CELL_W bits, the leftmost pixel in the lowest bit, a set bit a
light pixel.
"""
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

FONT = "/usr/share/fonts/abattis-cantarell-fonts/Cantarell-ExtraBold.otf"
SIZE = 76
CHARS = "0123456789-"


def glyphs(font_path):
    font = ImageFont.truetype(font_path, SIZE)
    ink = {}
    for ch in CHARS:
        im = Image.new("1", (SIZE * 2, SIZE * 2), 0)
        d = ImageDraw.Draw(im)
        d.fontmode = "1"
        d.text((SIZE // 2, SIZE // 4), ch, font=font, fill=1)
        ink[ch] = im
    # one cell for all: as wide as the widest digit, as tall as the tallest, aligned on the
    # digits' baseline (their common bottom) and centred across
    boxes = {ch: im.getbbox() for ch, im in ink.items()}
    digits = [boxes[c] for c in "0123456789"]
    top = min(b[1] for b in digits)
    bottom = max(b[3] for b in digits)
    width = max(b[2] - b[0] for b in digits)
    cells = {}
    for ch, im in ink.items():
        l, _, r, _ = boxes[ch]
        left = l - (width - (r - l)) // 2
        cells[ch] = im.crop((left, top, left + width, bottom))
    return cells, width, bottom - top


def to_rust(cells, width, height):
    assert width <= 64
    lines = [
        "// Generated by assets/clock.py -- edit that, not this.",
        "// Cantarell ExtraBold's digits (SIL Open Font License 1.1), rendered 1 bit.",
        "#![cfg_attr(rustfmt, rustfmt_skip)]",
        f"pub const CELL_W: usize = {width};",
        f"pub const CELL_H: usize = {height};",
        f"/// {CHARS!r}, a row of bits each (the leftmost pixel lowest), set for light.",
        f"pub const GLYPHS: [[u64; CELL_H]; {len(CHARS)}] = [",
    ]
    for ch in CHARS:
        im = cells[ch]
        rows = []
        for y in range(height):
            v = 0
            for x in range(width):
                if im.getpixel((x, y)):
                    v |= 1 << x
            rows.append(f"0x{v:016x}")
        lines.append(f"  // {ch!r}")
        for i in range(0, len(rows), 4):
            lines.append("  " + ("[" if i == 0 else " ") + ", ".join(rows[i:i + 4]) + ("]," if i + 4 >= len(rows) else ","))
    lines.append("];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent
    font = sys.argv[sys.argv.index("--font") + 1] if "--font" in sys.argv else FONT
    cells, width, height = glyphs(font)
    (here.parent / "src" / "clock_face.rs").write_text(to_rust(cells, width, height))
    print(f"src/clock_face.rs: {len(CHARS)} glyphs, {width}x{height}")
    if "--preview" in sys.argv:
        sheet = Image.new("1", (len(CHARS) * (width + 4), height), 0)
        for i, ch in enumerate(CHARS):
            sheet.paste(cells[ch], (i * (width + 4), 0))
        sheet.convert("L").resize((sheet.width * 2, sheet.height * 2), Image.NEAREST).save(sys.argv[sys.argv.index("--preview") + 1])
