#!/usr/bin/env python3
"""Draw the maki boot image and write it as src/splash.rs.

A maki roll, face on: the nori's ring around the rice, the filling at the middle, and
"maki" beneath in the launcher's tall font (read from blitstr2, so it matches the text maki
draws itself). 128x128, 1 bit, drawn procedurally so there is no Inkscape/PIL step; rerun
after editing. Output matches the dc34-vault bitmap convention (pngtorust.py): mirrored
left-right, 32 pixels per word MSB-first, a set bit is a dark pixel, and each row's four
words are written in reverse.

    python3 assets/splash.py [--preview OUT.png]
"""
import math
import pathlib
import re
import struct
import sys
import zlib

W = H = 128
CX, CY = 63.5, 52.0       # centre of the roll
NORI_OUT, NORI_IN = 40, 33
FILLING = 11
WORD_Y = 100              # top of "maki"
SAMPLES = 4               # per pixel, each way: edges go light when half covered

FONT = pathlib.Path(__file__).resolve().parents[3] / "libs" / "blitstr2" / "src" / "fonts" / "tall.rs"


def roll(x, y):
    d = math.hypot(x - CX, y - CY)
    return NORI_IN <= d <= NORI_OUT or d <= FILLING


def tall_font():
    src = FONT.read_text()

    def array(name):
        body = re.search(r"pub const %s: \[\w+; \d+\] = \[(.*?)\];" % name, src, re.S).group(1)
        return [int(v, 0) for v in re.findall(r"0x[0-9A-Fa-f]+|\b\d+\b", body)]

    return array("CODEPOINTS"), array("GLYPHS"), array("WIDTHS"), int(re.search(r"MAX_HEIGHT: u8 = (\d+)", src).group(1))


def word(text):
    """The light pixels of `text` in the tall font (32-pixel rows, least significant bit
    leftmost, one glyph after another with a pixel between), and its width."""
    codepoints, glyphs, widths, height = tall_font()
    lit, pen = set(), 0
    for ch in text:
        n = codepoints.index(ord(ch))
        for row, bits in enumerate(glyphs[n * 32:n * 32 + height]):
            for col in range(32):
                if bits >> col & 1:
                    lit.add((pen + col, row))
        pen += widths[n] + 1
    return lit, pen - 1


def pixels():
    px = []
    for y in range(H):
        row = []
        for x in range(W):
            hits = sum(roll(x + (i + 0.5) / SAMPLES, y + (j + 0.5) / SAMPLES)
                       for i in range(SAMPLES) for j in range(SAMPLES))
            row.append(hits * 2 >= SAMPLES * SAMPLES)
        px.append(row)
    lit, width = word("maki")
    left = (W - width) // 2
    for x, y in lit:
        px[WORD_Y + y][left + x] = True
    return px


def to_words(px):
    words = []
    for row in px:
        mirrored = row[::-1]
        row_words = []
        for w in range(4):
            v = 0
            for i, on in enumerate(mirrored[w * 32:(w + 1) * 32]):
                if not on:
                    v |= 1 << (31 - i)
            row_words.append(v)
        words.extend(row_words)
    return words


def write_rs(words, path):
    lines = ["// Generated by assets/splash.py -- edit that, not this.",
             "#![cfg_attr(rustfmt, rustfmt_skip)]",
             "pub const BITMAP: [u32; 512] = ["]
    for i in range(0, 512, 4):
        lines.append("  0x{:08x}, 0x{:08x}, 0x{:08x}, 0x{:08x},".format(
            words[i + 3], words[i + 2], words[i + 1], words[i]))
    lines.append("];")
    path.write_text("\n".join(lines) + "\n")


def write_png(px, path, scale=3):
    raw = b"".join(
        b"\x00" + bytes(255 if px[y // scale][x // scale] else 0 for x in range(W * scale))
        for y in range(H * scale))
    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W * scale, H * scale, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    pathlib.Path(path).write_bytes(png)


if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent
    px = pixels()
    write_rs(to_words(px), here.parent / "src" / "splash.rs")
    if "--preview" in sys.argv:
        write_png(px, sys.argv[sys.argv.index("--preview") + 1])
