#!/usr/bin/env python3
"""Draw the maki boot image and write it as src/splash.rs.

A steamed bao with a keyhole, 128x128, 1 bit. Drawn procedurally so there is no
Inkscape/PIL step; rerun after editing. Output matches the dc34-vault bitmap
convention (pngtorust.py): mirrored left-right, 32 pixels per word MSB-first,
a set bit is a dark pixel, and each row's four words are written in reverse.

    python3 assets/splash.py [--preview OUT.png]
"""
import math
import pathlib
import struct
import sys
import zlib

W = H = 128
CX = 64


def in_ellipse(x, y, cx, cy, rx, ry):
    return ((x - cx) / rx) ** 2 + ((y - cy) / ry) ** 2 <= 1.0


def near_segment(x, y, a, b, width):
    (ax, ay), (bx, by) = a, b
    dx, dy = bx - ax, by - ay
    t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)))
    px, py = ax + t * dx, ay + t * dy
    return (x - px) ** 2 + (y - py) ** 2 <= (width / 2) ** 2


# The bun is the top half of an ellipsoid seen from slightly above, so the pinched
# knot sits on the visible top surface, over a flatter base.
RX, RY, RZ = 46, 40, 46   # half-width, height, depth
CY = 78                   # centre of the bun's widest point
TILT = math.radians(28)   # how far we look down onto it
TOP = math.sqrt((RY * math.cos(TILT)) ** 2 + (RZ * math.sin(TILT)) ** 2)


def project(theta, phi):
    """Point at polar angle theta from the knot, azimuth phi, to screen x/y."""
    x = RX * math.sin(theta) * math.sin(phi)
    y = RY * math.cos(theta)
    z = RZ * math.sin(theta) * math.cos(phi)
    return CX + x, CY - (y * math.cos(TILT) - z * math.sin(TILT))


KNOT = project(0.0, 0.0)


def bun(x, y):
    if y <= CY:
        return in_ellipse(x, y, CX, CY, RX, TOP)
    return in_ellipse(x, y, CX, CY, RX, 24)


# pleats: curves from the knot down the front of the dome, twisting as they go
PLEATS = []
for deg in (-70, -42, -14, 14, 42, 70):
    pts = []
    for i in range(16):
        theta = 0.10 + 0.52 * i / 15
        phi = math.radians(deg) + 0.55 * theta
        if math.cos(phi) > 0.05:   # only the side facing us
            pts.append(project(theta, phi))
    PLEATS.append(pts)


def pleat(x, y):
    if in_ellipse(x, y, KNOT[0], KNOT[1], 2.6, 2.2):
        return True
    for pts in PLEATS:
        for a, b in zip(pts, pts[1:]):
            if near_segment(x, y, a, b, 1.9):
                return True
    return False


def keyhole(x, y):
    if in_ellipse(x, y, CX, 82, 6.5, 6.5):
        return True
    if 85 <= y <= 96:
        half = 2.6 + (y - 85) * (3.0 / 11)
        return abs(x - CX) <= half
    return False


def steam(x, y):
    for x0 in (46, 64, 82):
        if 6 <= y <= 28:
            wx = x0 + 3.0 * math.sin((y - 6) * 2 * math.pi / 12)
            if abs(x - wx) <= 1.2:
                return True
    return False


def lit(x, y):
    if steam(x, y):
        return True
    if bun(x, y):
        return not (pleat(x, y) or keyhole(x, y))
    return False


def pixels():
    return [[lit(x + 0.5, y + 0.5) for x in range(W)] for y in range(H)]


def to_words(px):
    words = []
    for row in px:
        mirrored = row[::-1]
        row_words = []
        for w in range(4):
            v = 0
            for i, on in enumerate(mirrored[w * 32:(w + 1) * 32]):
                if not on:
                    v |= 1 << (31 - i)
            row_words.append(v)
        words.extend(row_words)
    return words


def write_rs(words, path):
    lines = ["// Generated by assets/splash.py -- edit that, not this.",
             "#![cfg_attr(rustfmt, rustfmt_skip)]",
             "pub const BITMAP: [u32; 512] = ["]
    for i in range(0, 512, 4):
        lines.append("  0x{:08x}, 0x{:08x}, 0x{:08x}, 0x{:08x},".format(
            words[i + 3], words[i + 2], words[i + 1], words[i]))
    lines.append("];")
    path.write_text("\n".join(lines) + "\n")


def write_png(px, path, scale=3):
    raw = b"".join(
        b"\x00" + bytes(255 if px[y // scale][x // scale] else 0 for x in range(W * scale))
        for y in range(H * scale))
    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    png = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", W * scale, H * scale, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")
    pathlib.Path(path).write_bytes(png)


if __name__ == "__main__":
    here = pathlib.Path(__file__).resolve().parent
    px = pixels()
    write_rs(to_words(px), here.parent / "src" / "splash.rs")
    if "--preview" in sys.argv:
        write_png(px, sys.argv[sys.argv.index("--preview") + 1])
