[package]
name = "maki-apps"
version = "0.1.0"
edition = "2021"
description = "maki's own apps, in one process: Passkeys"

[dependencies]
log = "0.4.14"
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
xous = "0.9.66"
log-server = { package = "xous-api-log", version = "0.1.65" }
xous-names = { package = "xous-api-names", version = "0.9.67" }
blitstr2 = { path = "../../libs/blitstr2" }
maki-ui = { path = "../../libs/maki-ui" }
maki-icons = { path = "../../libs/maki-icons" }
maki-launcher = { path = "../maki-launcher" }
maki-keys = { package = "maki-keys-api", path = "../../libs/maki-keys-api" }
pddb = { path = "../../services/pddb" }
maki-proto = { path = "../../libs/maki-proto" }
maki-fido = { path = "../../libs/maki-fido" }

[features]
board-baosec = ["maki-ui/board-baosec", "blitstr2/board-baosec", "pddb/board-baosec"]
hosted-baosec = ["maki-ui/hosted-baosec"]
default = []
